import prisma from '@utils/db/db';
import Role from './Role';
import SuperadminGuard from './SuperadminGuard';

export default class RoleDB {
    static async CreateRole(roleData) {
        try {
            // Remove fields that should be auto-generated by database
            const { ID, CreatedAt, UpdatedAt, ...cleanRoleData } = roleData;

            // Debug logging
            if (process.env.NEXT_PUBLIC_MODE === 'DEV') {
                console.log('CreateRole received data:', roleData);
                console.log('CreateRole cleaned data:', cleanRoleData);
            }

            const role = new Role(cleanRoleData);
            const validationErrors = role.validate();

            if (validationErrors.length > 0) {
                return {
                    success: false,
                    message: 'Validation failed',
                    errors: validationErrors
                };
            }

            // Check if role name already exists
            const existingRole = await prisma.Role.findUnique({
                where: { Name: role.Name }
            });

            if (existingRole) {
                return {
                    success: false,
                    message: `Role with name "${role.Name}" already exists`,
                    errors: ['Duplicate role name']
                };
            }

            // Auto-assign priority: Get the highest priority + 1
            let priority = role.Priority;
            if (!priority) {
                const highestPriorityRole = await prisma.Role.findFirst({
                    orderBy: { Priority: 'desc' }
                });
                priority = highestPriorityRole ? highestPriorityRole.Priority + 1 : 1;
            }

            const newRole = await prisma.Role.create({
                data: {
                    Name: role.Name,
                    Description: role.Description,
                    Color: role.Color,
                    Priority: priority,
                    // ParentRoleID: role.ParentRoleID, // Temporarily disabled
                    // InheritPermissions: role.InheritPermissions, // Temporarily disabled
                    IsSystem: role.IsSystem,
                    IsActive: role.IsActive
                }
            });

            return {
                success: true,
                message: 'Role created successfully',
                data: new Role(newRole)
            };
        } catch (error) {
            console.error('Error creating role:', error);

            // Handle Prisma unique constraint violations
            if (error.code === 'P2002') {
                const field = error.meta?.target?.[0] || 'unknown field';
                return {
                    success: false,
                    message: `A role with this ${field === 'Name' ? 'name' : field} already exists`,
                    errors: [`Duplicate ${field}`],
                    error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
                };
            }

            return {
                success: false,
                message: 'Failed to create role',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async FetchRoles(filters = {}) {
        try {
            const {
                id,
                name,
                isActive,
                isSystem,
                return: returnFields,
                order_by: orderBy
            } = filters;

            let where = {};

            if (id) where.ID = parseInt(id);
            if (name) where.Name = { contains: name, mode: 'insensitive' };
            if (isActive !== undefined) where.IsActive = isActive;
            if (isSystem !== undefined) where.IsSystem = isSystem;

            let select = undefined;
            if (returnFields) {
                const allowedFields = ['ID', 'Name', 'Description', 'Color', 'Priority', 'IsSystem', 'IsActive', 'CreatedAt', 'UpdatedAt']; // Temporarily removed: 'ParentRoleID', 'InheritPermissions'
                const fields = returnFields
                    .split(',')
                    .map(f => f.trim())
                    .filter(f => allowedFields.includes(f));

                if (fields.length > 0) {
                    select = {};
                    fields.forEach(field => {
                        select[field] = true;
                    });
                }
            }

            let orderByClause = undefined;
            if (orderBy) {
                try {
                    const parsed = JSON.parse(orderBy);
                    const allowedColumns = ['ID', 'Name', 'Priority', 'CreatedAt', 'UpdatedAt'];
                    orderByClause = parsed
                        .filter(entry =>
                            entry.column &&
                            allowedColumns.includes(entry.column) &&
                            typeof entry.ascending === 'boolean'
                        )
                        .map(entry => ({
                            [entry.column]: entry.ascending ? 'asc' : 'desc'
                        }));
                } catch (err) {
                    console.warn("Invalid order_by format:", err.message);
                }
            }

            const roles = await prisma.Role.findMany({
                where,
                select,
                orderBy: orderByClause || [{ Priority: 'asc' }, { Name: 'asc' }]
            });

            return {
                success: true,
                data: roles.map(role => new Role(role))
            };
        } catch (error) {
            console.error('Error fetching roles:', error);
            return {
                success: false,
                message: 'Failed to fetch roles',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async FetchRoleById(id) {
        try {
            const roleId = parseInt(id);
            if (isNaN(roleId)) {
                return {
                    success: false,
                    message: 'Invalid role ID'
                };
            }

            const role = await prisma.Role.findUnique({
                where: { ID: roleId },
                include: {
                    RolePermissions: {
                        include: {
                            Permission: true
                        }
                    },
                    UserRoles: {
                        include: {
                            UserProfile: {
                                select: {
                                    ID: true,
                                    UserID: true,
                                    UserEmail: true
                                }
                            }
                        }
                    }
                }
            });

            if (!role) {
                return {
                    success: false,
                    message: 'Role not found'
                };
            }

            return {
                success: true,
                data: new Role(role)
            };
        } catch (error) {
            console.error('Error fetching role by ID:', error);
            return {
                success: false,
                message: 'Failed to fetch role',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async UpdateRole(id, updateData) {
        try {
            const roleId = parseInt(id);
            if (isNaN(roleId)) {
                return {
                    success: false,
                    message: 'Invalid role ID'
                };
            }

            // Check if role exists
            const existingRole = await prisma.Role.findUnique({
                where: { ID: roleId }
            });

            if (!existingRole) {
                return {
                    success: false,
                    message: 'Role not found'
                };
            }

            // Check if role is system role and if developer override is enabled
            const isDeveloperOverride = updateData._developerOverride === true;
            delete updateData._developerOverride; // Remove the flag from update data

            if (existingRole.IsSystem && !isDeveloperOverride) {
                return {
                    success: false,
                    message: 'Cannot modify system roles. Use developer override to bypass this restriction.'
                };
            }

            // Log developer override usage for audit purposes
            if (existingRole.IsSystem && isDeveloperOverride) {
                console.log(`⚠️ DEVELOPER OVERRIDE: Modifying system role "${existingRole.Name}" (ID: ${roleId})`);
            }

            // Validate update data
            const role = new Role({ ...existingRole, ...updateData });
            const validationErrors = role.validate();

            if (validationErrors.length > 0) {
                return {
                    success: false,
                    message: 'Validation failed',
                    errors: validationErrors
                };
            }

            const updatedRole = await prisma.Role.update({
                where: { ID: roleId },
                data: {
                    Name: role.Name,
                    Description: role.Description,
                    Color: role.Color,
                    Priority: role.Priority,
                    // ParentRoleID: role.ParentRoleID, // Temporarily disabled
                    // InheritPermissions: role.InheritPermissions, // Temporarily disabled
                    IsActive: role.IsActive,
                    UpdatedAt: new Date()
                }
            });

            return {
                success: true,
                message: `Role updated successfully${existingRole.IsSystem && isDeveloperOverride ? ' (Developer Override Used)' : ''}`,
                data: new Role(updatedRole)
            };
        } catch (error) {
            console.error('Error updating role:', error);
            return {
                success: false,
                message: 'Failed to update role',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async DeleteRole(id, options = {}) {
        try {
            const roleId = parseInt(id);
            if (isNaN(roleId)) {
                return {
                    success: false,
                    message: 'Invalid role ID'
                };
            }

            // Check if role exists
            const existingRole = await prisma.Role.findUnique({
                where: { ID: roleId }
            });

            if (!existingRole) {
                return {
                    success: false,
                    message: 'Role not found'
                };
            }

            // Check if role is system role and if developer override is enabled
            const isDeveloperOverride = options._developerOverride === true;

            if (existingRole.IsSystem && !isDeveloperOverride) {
                return {
                    success: false,
                    message: 'Cannot delete system roles. Use developer override to bypass this restriction.'
                };
            }

            // Log developer override usage for audit purposes
            if (existingRole.IsSystem && isDeveloperOverride) {
                console.log(`⚠️ DEVELOPER OVERRIDE: Deleting system role "${existingRole.Name}" (ID: ${roleId})`);
            }

            // Check if role has users
            const usersWithRole = await prisma.UserRole.findMany({
                where: { RoleID: roleId }
            });

            if (usersWithRole.length > 0) {
                return {
                    success: false,
                    message: 'Cannot delete role with assigned users'
                };
            }

            // Delete role permissions first
            await prisma.RolePermission.deleteMany({
                where: { RoleID: roleId }
            });

            // Delete the role
            await prisma.Role.delete({
                where: { ID: roleId }
            });

            return {
                success: true,
                message: `Role deleted successfully${existingRole.IsSystem && isDeveloperOverride ? ' (Developer Override Used)' : ''}`
            };
        } catch (error) {
            console.error('Error deleting role:', error);
            return {
                success: false,
                message: 'Failed to delete role',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async AssignRoleToUser(userProfileId, roleId, assignedBy = null) {
        try {
            const userProfileIdInt = parseInt(userProfileId);
            const roleIdInt = parseInt(roleId);

            if (isNaN(userProfileIdInt) || isNaN(roleIdInt)) {
                return {
                    success: false,
                    message: 'Invalid user profile ID or role ID'
                };
            }

            // Check if user profile exists
            const userProfile = await prisma.UserProfile.findUnique({
                where: { ID: userProfileIdInt }
            });

            if (!userProfile) {
                return {
                    success: false,
                    message: 'User profile not found'
                };
            }

            // Check if role exists
            const role = await prisma.Role.findUnique({
                where: { ID: roleIdInt }
            });

            if (!role) {
                return {
                    success: false,
                    message: 'Role not found'
                };
            }

            // Check if role is active
            if (!role.IsActive) {
                return {
                    success: false,
                    message: 'Cannot assign inactive role'
                };
            }

            // Check if user already has this role
            const existingUserRole = await prisma.UserRole.findUnique({
                where: {
                    UserProfileID_RoleID: {
                        UserProfileID: userProfileIdInt,
                        RoleID: roleIdInt
                    }
                }
            });

            if (existingUserRole) {
                return {
                    success: false,
                    message: 'User already has this role'
                };
            }

            // Assign role to user
            const userRole = await prisma.UserRole.create({
                data: {
                    UserProfileID: userProfileIdInt,
                    RoleID: roleIdInt,
                    AssignedBy: assignedBy ? parseInt(assignedBy) : null,
                    AssignedAt: new Date()
                }
            });

            return {
                success: true,
                message: 'Role assigned successfully',
                data: userRole
            };
        } catch (error) {
            console.error('Error assigning role to user:', error);
            return {
                success: false,
                message: 'Failed to assign role to user',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async RemoveRoleFromUser(userProfileId, roleId) {
        try {
            const userProfileIdInt = parseInt(userProfileId);
            const roleIdInt = parseInt(roleId);

            if (isNaN(userProfileIdInt) || isNaN(roleIdInt)) {
                return {
                    success: false,
                    message: 'Invalid user profile ID or role ID'
                };
            }

            // Check if trying to remove Superadmin role from the last active Superadmin
            const removalCheck = await SuperadminGuard.canRemoveSuperadminRole(userProfileIdInt, roleIdInt);
            if (!removalCheck.allowed) {
                return {
                    success: false,
                    message: removalCheck.message
                };
            }

            // Check if user role exists
            const existingUserRole = await prisma.UserRole.findUnique({
                where: {
                    UserProfileID_RoleID: {
                        UserProfileID: userProfileIdInt,
                        RoleID: roleIdInt
                    }
                }
            });

            if (!existingUserRole) {
                return {
                    success: false,
                    message: 'User does not have this role'
                };
            }

            // Remove role from user
            await prisma.UserRole.delete({
                where: {
                    UserProfileID_RoleID: {
                        UserProfileID: userProfileIdInt,
                        RoleID: roleIdInt
                    }
                }
            });

            return {
                success: true,
                message: 'Role removed successfully'
            };
        } catch (error) {
            console.error('Error removing role from user:', error);
            return {
                success: false,
                message: 'Failed to remove role from user',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async GetUserRoles(userProfileId) {
        try {
            const userProfileIdInt = parseInt(userProfileId);
            if (isNaN(userProfileIdInt)) {
                return {
                    success: false,
                    message: 'Invalid user profile ID'
                };
            }

            const userRoles = await prisma.UserRole.findMany({
                where: { UserProfileID: userProfileIdInt },
                include: {
                    Role: true
                }
            });

            return {
                success: true,
                data: userRoles.map(userRole => ({
                    ...userRole,
                    Role: new Role(userRole.Role)
                }))
            };
        } catch (error) {
            console.error('Error getting user roles:', error);
            return {
                success: false,
                message: 'Failed to get user roles',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }

    static async ReorderRoles(roleOrders) {
        try {
            // roleOrders is an array of { id, priority }
            // Update all roles with their new priorities in a transaction
            await prisma.$transaction(
                roleOrders.map(({ id, priority }) =>
                    prisma.Role.update({
                        where: { ID: parseInt(id) },
                        data: { Priority: priority }
                    })
                )
            );

            return {
                success: true,
                message: 'Roles reordered successfully'
            };
        } catch (error) {
            console.error('Error reordering roles:', error);
            return {
                success: false,
                message: 'Failed to reorder roles',
                error: process.env.NEXT_PUBLIC_MODE === 'DEV' ? error.message : undefined
            };
        }
    }
}
