import { TokenValidation } from "@app/api/api_helper";
import nodemailer from "nodemailer";
import { NextResponse } from "next/server";

function GenerateUniqueSubject(base) {
	const timestamp = new Date().toISOString().replace(/[-:.TZ]/g, "");
	return `${base} [${timestamp}]`;
}

export async function POST(req) {
	try {
		// Check for DEV override
		const isDevOverride = req.headers.get('x-dev-override') === 'true' &&
			process.env.NEXT_PUBLIC_MODE === 'DEV';

		if (!isDevOverride) {
			const authHeader = req.headers.get('Authorization');
			const token_res = TokenValidation(authHeader);

			if (!token_res.success) {
				return NextResponse.json({ success: false, message: token_res.message }, { status: token_res.status });
			}
			// Require actor email for auditability
			const sessionEmail = req.headers.get('x-session-email');
			if (!sessionEmail) {
				return NextResponse.json({ success: false, message: 'Missing authentication header x-session-email' }, { status: 401 });
			}
		}

		const body = await req.json();
		const { 
			student_name, 
			student_id, 
			recipients, 
			email_subject, 
			email_content, 
			url_link, 
			pdf_base64, 
			filename 
		} = body;

		// Validate recipients
		if (!recipients || !Array.isArray(recipients) || recipients.length === 0) {
			return NextResponse.json({ 
				success: false, 
				error: 'Recipients must be a non-empty array' 
			}, { status: 400 });
		}

		// Validate email format for all recipients
		const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
		const invalidEmails = recipients.filter(email => !emailRegex.test(email));
		
		if (invalidEmails.length > 0) {
			return NextResponse.json({ 
				success: false, 
				error: `Invalid email format: ${invalidEmails.join(', ')}` 
			}, { status: 400 });
		}

		// Configure Gmail SMTP transporter
		const transporter = nodemailer.createTransport({
			service: "gmail",
			auth: {
				user: process.env.GMAIL_EMAIL,
				pass: process.env.GMAIL_APP_PW,
			},
		});

		// Use the provided HTML content directly (already in HTML format from Quill editor)
		const htmlContent = email_content || `
			<h2 style="color: #004080;">Hello,</h2>
			
			<p>
			Your <strong>Personalized Study Planner</strong> for <strong>${student_name}</strong> 
			(Student ID: <strong>${student_id}</strong>) is now ready.  
			You can view it using the attached PDF file.
			</p>

			<p>
			Please note that this planner was automatically generated by <strong>Swinburne Sarawak FYP Group 3 Students</strong> 
			for reference purposes only. It is <strong>not an official document from Swinburne University of Technology, Sarawak</strong>.
			</p>

			<p>
			If you have any questions, you may contact your course coordinator.
			</p>
		`;

		// Send email with PDF attachment to all recipients
		const info = await transporter.sendMail({
			from: `"Study Planner" <${process.env.GMAIL_EMAIL}>`,
			to: recipients.join(', '), // Join all recipients
			subject: GenerateUniqueSubject(email_subject || `Study Planner for ${student_name} (ID: ${student_id})`),
			html: `
				<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; color: #333;">
					${htmlContent}

					<hr style="margin: 30px 0; border: none; border-top: 1px solid #ccc;" />

					<p style="font-size: 0.9rem; color: #555;">
					This email was sent by Swinburne Sarawak FYP Group 3 Students as part of a student project.  
					Please keep this planner for your reference only.
					</p>
				</div>
			`,
			attachments: [
				{
					filename: filename,
					content: Buffer.from(pdf_base64, "base64"),
					contentType: "application/pdf",
				},
			],
		});

		return NextResponse.json({ 
			success: true, 
			messageId: info.messageId,
			recipientCount: recipients.length
		});
	} catch (error) {
		console.error("Email send failed:", error);
		return NextResponse.json({ 
			success: false, 
			error: error.message 
		}, { status: 500 });
	}
}